# ── .github/workflows/update.yml ──
name: Update stocks.json daily

on:
  schedule:
    - cron: '0 21 * * *'  # JST 6:00 (UTC 21:00)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install requests
        run: pip install requests yfinance

      - name: Run update script
        run: python update_stocks.py

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          # 変更がある場合のみコミット＆プッシュ
          if [[ -n "$(git status --porcelain stocks.json)" ]]; then
            git add stocks.json
            git commit -m "Auto-update stocks.json"
            git push
          else
            echo "No changes to commit."
          fi
